package net.sahet.autovalue.demo;

import java.util.List;
import java.util.Optional;

import com.google.auto.value.AutoValue;

/**
 * <pre>
	Generated the Builder pattern by default? 🔴
	Generated helper methods for, i.e., Optional and List? 🔴  
	The number of lines of code to write? 28 ✅
	It requires IDE plugin 🔴
	Are the objects immutable? 🔴  
 * </pre>
 *
 */
@AutoValue
public abstract class MyModel {
	public abstract Optional<Integer> myOptional();

	public abstract String myString();

	public abstract List<String> myList();

	// Builder not generated by default
	// We have to write this boilerplate code
	@AutoValue.Builder
	public abstract static class Builder {
		public abstract Builder setMyOptional(Optional<Integer> myOptional);

		public abstract Builder setMyString(String myString);

		public abstract Builder setMyList(List<String> myList);

		public abstract MyModel build();
	}
}